---
baseurl: "/"
permalink: "/:title/"
title: Snipcart
snipcart_js: https://cdn.snipcart.com/themes/v3.0.4/default/snipcart.js
snipcart_css: https://cdn.snipcart.com/themes/v3.0.4/default/snipcart.css
snipcart_api_key: YTA2YWRkYTMtMTAyYi00YTZjLWJiZWMtYTVmZTA2NjViN2ExNjM3MTQ4ODgyNTU3NTc2NDEz
logos:
  light:
    optimized: "/images/logo-horiz-white.svg"
    fallback: "/images/logo-horiz-white.svg"
  dark:
    optimized: "/images/logo-horiz.svg"
    fallback: "/images/logo-horiz.svg"
palette: default
palettes:
  default:
    sass:
      default: "#FFFFFF"
      light: "#F0F0F0"
      medium: "#6B797A"
      dark: "#384647"
      active: "#0cc2f2"
      active_light: "#C0FDB6"
      active_medium: "#5C9174"
      active_dark: "#547567"
      dark_grey: "#273132"
      light_grey: "#6B797A"
      bg_image_primary_optimized: "/images/hero.jpg"
      bg_image_primary_fallback: "/images/hero.jpg"
      bg_image_secondary_optimized: "/images/logo-symbol-light.svg"
      bg_image_secondary_fallback: "/images/logo-symbol-light.svg"
      bg_image_product_optimized: "/images/logo-symbol.svg"
      bg_image_product_fallback: "/images/logo-symbol.svg"
      bg_image_cart_optimized: "/images/hero.jpg"
      bg_image_cart_fallback: "/images/hero.jpg"
sass:
  style: nested
  precision: 10
plugins:
- jekyll-menus
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- ssg-build.sh
- LICENSE.md
- README.md
- netlify.toml
- stackbit-build.sh
- stackbit-pull.js
collections:
  posts:
    permalink: "/posts/:title/"
